/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AppStandupRouteImport } from './routes/app/standup'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppTeamTeamIdRouteImport } from './routes/app/team.$teamId'
import { Route as AppSettingsTeamsRouteImport } from './routes/app/settings/teams'
import { Route as AppSettingsMembersRouteImport } from './routes/app/settings/members'
import { Route as AppSettingsBillingRouteImport } from './routes/app/settings/billing'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStandupRoute = AppStandupRouteImport.update({
  id: '/standup',
  path: '/standup',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeamTeamIdRoute = AppTeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsTeamsRoute = AppSettingsTeamsRouteImport.update({
  id: '/settings/teams',
  path: '/settings/teams',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/history': typeof AppHistoryRoute
  '/app/standup': typeof AppStandupRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/teams': typeof AppSettingsTeamsRoute
  '/app/team/$teamId': typeof AppTeamTeamIdRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/history': typeof AppHistoryRoute
  '/app/standup': typeof AppStandupRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/teams': typeof AppSettingsTeamsRoute
  '/app/team/$teamId': typeof AppTeamTeamIdRoute
  '/app/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/history': typeof AppHistoryRoute
  '/app/standup': typeof AppStandupRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/teams': typeof AppSettingsTeamsRoute
  '/app/team/$teamId': typeof AppTeamTeamIdRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/history'
    | '/app/standup'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/app/settings/billing'
    | '/app/settings/members'
    | '/app/settings/teams'
    | '/app/team/$teamId'
    | '/app/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/history'
    | '/app/standup'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/app/settings/billing'
    | '/app/settings/members'
    | '/app/settings/teams'
    | '/app/team/$teamId'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/history'
    | '/app/standup'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/app/settings/billing'
    | '/app/settings/members'
    | '/app/settings/teams'
    | '/app/team/$teamId'
    | '/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/standup': {
      id: '/app/standup'
      path: '/standup'
      fullPath: '/app/standup'
      preLoaderRoute: typeof AppStandupRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/team/$teamId': {
      id: '/app/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/app/team/$teamId'
      preLoaderRoute: typeof AppTeamTeamIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/teams': {
      id: '/app/settings/teams'
      path: '/settings/teams'
      fullPath: '/app/settings/teams'
      preLoaderRoute: typeof AppSettingsTeamsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/members': {
      id: '/app/settings/members'
      path: '/settings/members'
      fullPath: '/app/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/billing': {
      id: '/app/settings/billing'
      path: '/settings/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppStandupRoute: typeof AppStandupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsTeamsRoute: typeof AppSettingsTeamsRoute
  AppTeamTeamIdRoute: typeof AppTeamTeamIdRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppStandupRoute: AppStandupRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsTeamsRoute: AppSettingsTeamsRoute,
  AppTeamTeamIdRoute: AppTeamTeamIdRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
