/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AppStandupRouteImport } from './routes/app/standup'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppTeamTeamIdRouteImport } from './routes/app/team.$teamId'
import { Route as AppSettingsTeamsRouteImport } from './routes/app/settings/teams'
import { Route as AppSettingsMembersRouteImport } from './routes/app/settings/members'
import { Route as AppSettingsBillingRouteImport } from './routes/app/settings/billing'
import { Route as AppSettingsApiKeysRouteImport } from './routes/app/settings/api-keys'
import { Route as AppSettingsApiDocsRouteImport } from './routes/app/settings/api-docs'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiPublicSplatRouteImport } from './routes/api/public/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStandupRoute = AppStandupRouteImport.update({
  id: '/standup',
  path: '/standup',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeamTeamIdRoute = AppTeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsTeamsRoute = AppSettingsTeamsRouteImport.update({
  id: '/settings/teams',
  path: '/settings/teams',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsApiDocsRoute = AppSettingsApiDocsRouteImport.update({
  id: '/settings/api-docs',
  path: '/settings/api-docs',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSplatRoute = ApiPublicSplatRouteImport.update({
  id: '/api/public/$',
  path: '/api/public/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/standup': typeof AppStandupRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/settings/api-docs': typeof AppSettingsApiDocsRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/teams': typeof AppSettingsTeamsRoute
  '/app/team/$teamId': typeof AppTeamTeamIdRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/standup': typeof AppStandupRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/share/$token': typeof ShareTokenRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/settings/api-docs': typeof AppSettingsApiDocsRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/teams': typeof AppSettingsTeamsRoute
  '/app/team/$teamId': typeof AppTeamTeamIdRoute
  '/app/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/standup': typeof AppStandupRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/settings/api-docs': typeof AppSettingsApiDocsRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/teams': typeof AppSettingsTeamsRoute
  '/app/team/$teamId': typeof AppTeamTeamIdRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/privacy'
    | '/terms'
    | '/api/mcp'
    | '/app/analytics'
    | '/app/history'
    | '/app/standup'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/share/$token'
    | '/app/'
    | '/api/auth/$'
    | '/api/public/$'
    | '/api/trpc/$'
    | '/app/settings/api-docs'
    | '/app/settings/api-keys'
    | '/app/settings/billing'
    | '/app/settings/members'
    | '/app/settings/teams'
    | '/app/team/$teamId'
    | '/app/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/api/mcp'
    | '/app/analytics'
    | '/app/history'
    | '/app/standup'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/share/$token'
    | '/app'
    | '/api/auth/$'
    | '/api/public/$'
    | '/api/trpc/$'
    | '/app/settings/api-docs'
    | '/app/settings/api-keys'
    | '/app/settings/billing'
    | '/app/settings/members'
    | '/app/settings/teams'
    | '/app/team/$teamId'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/privacy'
    | '/terms'
    | '/api/mcp'
    | '/app/analytics'
    | '/app/history'
    | '/app/standup'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/share/$token'
    | '/app/'
    | '/api/auth/$'
    | '/api/public/$'
    | '/api/trpc/$'
    | '/app/settings/api-docs'
    | '/app/settings/api-keys'
    | '/app/settings/billing'
    | '/app/settings/members'
    | '/app/settings/teams'
    | '/app/team/$teamId'
    | '/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiMcpRoute: typeof ApiMcpRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPublicSplatRoute: typeof ApiPublicSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/standup': {
      id: '/app/standup'
      path: '/standup'
      fullPath: '/app/standup'
      preLoaderRoute: typeof AppStandupRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/team/$teamId': {
      id: '/app/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/app/team/$teamId'
      preLoaderRoute: typeof AppTeamTeamIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/teams': {
      id: '/app/settings/teams'
      path: '/settings/teams'
      fullPath: '/app/settings/teams'
      preLoaderRoute: typeof AppSettingsTeamsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/members': {
      id: '/app/settings/members'
      path: '/settings/members'
      fullPath: '/app/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/billing': {
      id: '/app/settings/billing'
      path: '/settings/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/api-keys': {
      id: '/app/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/app/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/api-docs': {
      id: '/app/settings/api-docs'
      path: '/settings/api-docs'
      fullPath: '/app/settings/api-docs'
      preLoaderRoute: typeof AppSettingsApiDocsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/$': {
      id: '/api/public/$'
      path: '/api/public/$'
      fullPath: '/api/public/$'
      preLoaderRoute: typeof ApiPublicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppStandupRoute: typeof AppStandupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsApiDocsRoute: typeof AppSettingsApiDocsRoute
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsTeamsRoute: typeof AppSettingsTeamsRoute
  AppTeamTeamIdRoute: typeof AppTeamTeamIdRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppStandupRoute: AppStandupRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsApiDocsRoute: AppSettingsApiDocsRoute,
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsTeamsRoute: AppSettingsTeamsRoute,
  AppTeamTeamIdRoute: AppTeamTeamIdRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiMcpRoute: ApiMcpRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPublicSplatRoute: ApiPublicSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
